use proptest::prelude::*;
use regex::Regex;
use ruby_synthesizer::{RubyNode, RubyType, emit_file, ruby_body, ruby_module, ruby_parent};

// ── Arbitrary implementations for property-based testing ─────────

fn arb_ruby_type() -> impl Strategy<Value = RubyType> {
    let leaf = prop_oneof![
        Just(RubyType::simple("T::String")),
        Just(RubyType::simple("T::Integer")),
        Just(RubyType::simple("T::Bool")),
        Just(RubyType::simple("T::Coercible::Float")),
        Just(RubyType::Hash),
        Just(RubyType::Any),
    ];

    leaf.prop_recursive(
        3,  // depth
        16, // max nodes
        4,  // items per collection
        |inner| {
            prop_oneof![
                inner.clone().prop_map(RubyType::array),
                inner.clone().prop_map(RubyType::optional),
                prop::collection::vec(inner.clone(), 2..=4).prop_map(RubyType::union),
                inner.prop_map(|t| RubyType::constrained(t, "included_in: ['a', 'b']")),
            ]
        },
    )
}

// ── RubyType property tests ──────────────────────────────────────

proptest! {
    /// Every type expression emits balanced parentheses.
    #[test]
    fn type_emit_balanced_parens(ty in arb_ruby_type()) {
        let emitted = ty.emit();
        let opens = emitted.matches('(').count();
        let closes = emitted.matches(')').count();
        prop_assert!(opens == closes, "unbalanced parens ({} opens, {} closes) in: {}", opens, closes, emitted);
    }

    /// Emit is deterministic: same type → same output.
    #[test]
    fn type_emit_deterministic(ty in arb_ruby_type()) {
        let a = ty.emit();
        let b = ty.emit();
        prop_assert_eq!(a, b);
    }

    /// Optional is idempotent: optional(optional(x)).emit() == optional(x).emit()
    #[test]
    fn optional_idempotent(ty in arb_ruby_type()) {
        let once = RubyType::optional(ty.clone());
        let twice = RubyType::optional(once.clone());
        prop_assert!(once.emit() == twice.emit(), "optional not idempotent");
    }

    /// No double .optional.optional in output.
    #[test]
    fn no_double_optional(ty in arb_ruby_type()) {
        let opt = RubyType::optional(ty);
        let emitted = opt.emit();
        prop_assert!(!emitted.contains(".optional.optional"),
            "double optional in: {emitted}");
    }

    /// Type emit never produces empty string.
    #[test]
    fn type_emit_nonempty(ty in arb_ruby_type()) {
        let emitted = ty.emit();
        prop_assert!(!emitted.is_empty());
    }
}

// ── RubyNode structural property tests ───────────────────────────

fn arb_attribute() -> impl Strategy<Value = RubyNode> {
    ("[a-z][a-z_]{1,10}", arb_ruby_type(), any::<bool>()).prop_map(|(name, ty, req)| {
        RubyNode::Attribute {
            name,
            type_expr: ty,
            required: req,
        }
    })
}

fn arb_class() -> impl Strategy<Value = RubyNode> {
    prop::collection::vec(arb_attribute(), 1..=5).prop_map(|attrs| {
        let mut body = vec![
            RubyNode::ConstAssign {
                name: "T".into(),
                value: "Pangea::Resources::Test::Types".into(),
            },
            RubyNode::Blank,
        ];
        body.extend(attrs);
        RubyNode::Class {
            name: "TestAttributes".into(),
            parent: Some("Pangea::Resources::BaseAttributes".into()),
            body,
        }
    })
}

fn arb_types_file() -> impl Strategy<Value = Vec<RubyNode>> {
    arb_class().prop_map(|class_node| {
        vec![
            RubyNode::FrozenStringLiteral,
            RubyNode::Comment("Code generated by ruby-synthesizer.".into()),
            RubyNode::Blank,
            RubyNode::Require("pangea/resources/base_attributes".into()),
            RubyNode::Blank,
            RubyNode::Module {
                path: vec![
                    "Pangea".into(),
                    "Resources".into(),
                    "Test".into(),
                    "Types".into(),
                ],
                body: vec![
                    RubyNode::Include("Dry.Types()".into()),
                    RubyNode::Blank,
                    class_node,
                ],
            },
        ]
    })
}

proptest! {
    /// Every generated types file has balanced module/class/end blocks.
    #[test]
    fn types_file_balanced_blocks(nodes in arb_types_file()) {
        let output = emit_file(&nodes);

        let module_re = Regex::new(r"(?m)^\s*module ").unwrap();
        let class_re = Regex::new(r"(?m)^\s*class ").unwrap();
        let end_re = Regex::new(r"(?m)^\s*end\s*$").unwrap();

        let openers = module_re.find_iter(&output).count()
            + class_re.find_iter(&output).count();
        let closers = end_re.find_iter(&output).count();

        prop_assert!(openers == closers, "unbalanced blocks: {} openers vs {} ends", openers, closers);
    }

    /// Every generated types file starts with frozen_string_literal.
    #[test]
    fn types_file_starts_with_pragma(nodes in arb_types_file()) {
        let output = emit_file(&nodes);
        prop_assert!(output.starts_with("# frozen_string_literal: true\n"),
            "missing pragma in:\n{output}");
    }

    /// Every generated types file contains BaseAttributes inheritance.
    #[test]
    fn types_file_has_base_attributes(nodes in arb_types_file()) {
        let output = emit_file(&nodes);
        prop_assert!(output.contains("< Pangea::Resources::BaseAttributes"),
            "missing BaseAttributes in:\n{output}");
    }

    /// Every non-blank line has consistent indentation (multiples of 2 spaces).
    #[test]
    fn consistent_indentation(nodes in arb_types_file()) {
        let output = emit_file(&nodes);
        for (i, line) in output.lines().enumerate() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let spaces = line.len() - line.trim_start().len();
            prop_assert!(spaces % 2 == 0,
                "line {} has {} leading spaces (not multiple of 2): '{}'", i + 1, spaces, line);
        }
    }

    /// Emit is deterministic for full files.
    #[test]
    fn file_emit_deterministic(nodes in arb_types_file()) {
        let a = emit_file(&nodes);
        let b = emit_file(&nodes);
        prop_assert_eq!(a, b);
    }

    /// Every attribute line matches the expected pattern.
    #[test]
    fn attribute_lines_valid(nodes in arb_types_file()) {
        let output = emit_file(&nodes);
        let attr_re = Regex::new(r"^\s+attribute\??\s+:\w+,\s+.+$").unwrap();
        for line in output.lines() {
            if line.trim_start().starts_with("attribute") {
                prop_assert!(attr_re.is_match(line),
                    "invalid attribute line: '{line}'");
            }
        }
    }
}

// ── Union invariant tests (not proptest — deterministic) ─────────

#[test]
fn union_single_degenerates() {
    let ty = RubyType::union(vec![RubyType::simple("T::String")]);
    assert_eq!(ty, RubyType::simple("T::String"));
}

#[test]
#[should_panic(expected = "0 variants is invalid")]
fn union_empty_panics() {
    RubyType::union(vec![]);
}

#[test]
fn union_two_produces_union() {
    let ty = RubyType::union(vec![
        RubyType::simple("T::String"),
        RubyType::simple("T::Integer"),
    ]);
    assert!(matches!(ty, RubyType::Union(_)));
}

// ── Macro parity tests ───────────────────────────────────────────

#[test]
fn macro_equals_manual_construction() {
    let manual = RubyNode::Module {
        path: vec!["A".into(), "B".into()],
        body: vec![RubyNode::Include("Dry.Types()".into())],
    };
    let via_macro = ruby_synthesizer::ruby_module!("A::B" => {
        include "Dry.Types()";
    });
    assert_eq!(manual, via_macro);
}

#[test]
fn macro_class_equals_manual() {
    let manual = RubyNode::Module {
        path: vec!["Test".into()],
        body: vec![RubyNode::Class {
            name: "Foo".into(),
            parent: Some("Bar".into()),
            body: vec![RubyNode::Attribute {
                name: "x".into(),
                type_expr: RubyType::simple("T::String"),
                required: true,
            }],
        }],
    };
    let via_macro = ruby_synthesizer::ruby_module!("Test" => {
        class "Foo" < "Bar" {
            attribute "x", RubyType::simple("T::String");
        }
    });
    assert_eq!(manual, via_macro);
}
