//! Validated builders — compile-time enforcement of valid Ruby structures.
//!
//! These builders make invalid nesting IMPOSSIBLE at the Rust compiler level:
//! - An Attribute can only exist inside a ClassBuilder
//! - A Class can only exist inside a TypesFileBuilder
//! - A DefineResource can only exist inside a ResourceFileBuilder
//!
//! The output is always a valid, well-formed Ruby source file.
//!
//! ```rust
//! use ruby_synthesizer::builders::TypesFileBuilder;
//! use ruby_synthesizer::RubyType;
//!
//! let source = TypesFileBuilder::new("porkbun")
//!     .class("NameserversAttributes", |c| {
//!         c.attribute("domain", RubyType::simple("T::String"), true)
//!          .attribute("nameservers", RubyType::array(RubyType::simple("T::String")), true)
//!     })
//!     .emit();
//!
//! assert!(source.contains("# frozen_string_literal: true"));
//! assert!(source.contains("class NameserversAttributes < Pangea::Resources::BaseAttributes"));
//! assert!(source.contains("attribute :domain, T::String"));
//! ```

use crate::node::RubyNode;
use crate::types::RubyType;
use crate::emitter::emit_file;

// ── Types File Builder ──────────────────────────────────────────

/// Builds a types.rb file with guaranteed structure:
/// frozen_string_literal → require → module → include → class → attributes
pub struct TypesFileBuilder {
    provider: String,
    provider_pascal: String,
    classes: Vec<ClassDef>,
}

struct ClassDef {
    name: String,
    attributes: Vec<(String, RubyType, bool)>,
}

/// Builder context for adding attributes to a class.
/// Only attribute-level operations are available — no module or file operations.
pub struct ClassBuilder {
    attributes: Vec<(String, RubyType, bool)>,
}

impl ClassBuilder {
    /// Add an attribute to this class.
    #[must_use]
    pub fn attribute(mut self, name: &str, ty: RubyType, required: bool) -> Self {
        self.attributes.push((name.to_string(), ty, required));
        self
    }
}

impl TypesFileBuilder {
    /// Create a new types file builder for a provider.
    #[must_use]
    pub fn new(provider: &str) -> Self {
        Self {
            provider: provider.to_string(),
            provider_pascal: to_pascal(provider),
            classes: Vec::new(),
        }
    }

    /// Add a class (struct) to this types file.
    /// The closure receives a `ClassBuilder` where only attributes can be added.
    #[must_use]
    pub fn class(mut self, name: &str, f: impl FnOnce(ClassBuilder) -> ClassBuilder) -> Self {
        let builder = f(ClassBuilder { attributes: Vec::new() });
        self.classes.push(ClassDef {
            name: name.to_string(),
            attributes: builder.attributes,
        });
        self
    }

    /// Emit the complete types.rb source file.
    #[must_use]
    pub fn emit(&self) -> String {
        let mut nodes = vec![
            RubyNode::FrozenStringLiteral,
            RubyNode::Comment("Code generated by pangea-forge. DO NOT EDIT.".into()),
            RubyNode::Blank,
            RubyNode::Require("pangea/resources/base_attributes".into()),
            RubyNode::Blank,
        ];

        let module_path = vec![
            "Pangea".into(), "Resources".into(),
            self.provider_pascal.clone(), "Types".into(),
        ];

        let mut module_body = vec![
            RubyNode::Include("Dry.Types()".into()),
            RubyNode::Blank,
        ];

        for class_def in &self.classes {
            let mut class_body = vec![
                RubyNode::ConstAssign {
                    name: "T".into(),
                    value: format!("Pangea::Resources::{}::Types", self.provider_pascal),
                },
            ];

            if !class_def.attributes.is_empty() {
                class_body.push(RubyNode::Blank);
            }

            for (attr_name, attr_type, required) in &class_def.attributes {
                class_body.push(RubyNode::Attribute {
                    name: attr_name.clone(),
                    type_expr: attr_type.clone(),
                    required: *required,
                });
            }

            module_body.push(RubyNode::Class {
                name: class_def.name.clone(),
                parent: Some("Pangea::Resources::BaseAttributes".into()),
                body: class_body,
            });
        }

        nodes.push(RubyNode::Module {
            path: module_path,
            body: module_body,
        });

        emit_file(&nodes)
    }
}

// ── Resource File Builder ───────────────────────────────────────

/// Builds a resource.rb file with guaranteed structure:
/// requires → module → define_resource → include → registry_call
pub struct ResourceFileBuilder {
    provider: String,
    provider_pascal: String,
    tf_type: String,
    module_name: String,
    attrs_class: String,
    outputs: Vec<(String, String)>,
    map: Vec<String>,
    map_present: Vec<String>,
    map_bool: Vec<String>,
}

impl ResourceFileBuilder {
    /// Create a new resource file builder.
    #[must_use]
    pub fn new(provider: &str, tf_type: &str, short_name: &str) -> Self {
        let pascal = to_pascal(provider);
        let class_pascal = to_pascal(short_name);
        Self {
            provider: provider.to_string(),
            provider_pascal: pascal.clone(),
            tf_type: tf_type.to_string(),
            module_name: format!("{pascal}{class_pascal}"),
            attrs_class: format!("{pascal}::Types::{class_pascal}Attributes"),
            outputs: vec![("id".into(), "id".into())],
            map: Vec::new(),
            map_present: Vec::new(),
            map_bool: Vec::new(),
        }
    }

    #[must_use]
    pub fn outputs(mut self, outputs: Vec<(&str, &str)>) -> Self {
        self.outputs = outputs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect();
        self
    }

    #[must_use]
    pub fn map(mut self, fields: Vec<&str>) -> Self {
        self.map = fields.iter().map(|s| s.to_string()).collect();
        self
    }

    #[must_use]
    pub fn map_present(mut self, fields: Vec<&str>) -> Self {
        self.map_present = fields.iter().map(|s| s.to_string()).collect();
        self
    }

    #[must_use]
    pub fn map_bool(mut self, fields: Vec<&str>) -> Self {
        self.map_bool = fields.iter().map(|s| s.to_string()).collect();
        self
    }

    /// Emit the complete resource.rb source file.
    #[must_use]
    pub fn emit(&self) -> String {
        let nodes = vec![
            RubyNode::FrozenStringLiteral,
            RubyNode::Comment("Code generated by pangea-forge. DO NOT EDIT.".into()),
            RubyNode::Blank,
            RubyNode::Require("pangea/resources/base".into()),
            RubyNode::Require("pangea/resources/reference".into()),
            RubyNode::Require(format!("pangea/resources/{}/types", self.tf_type)),
            RubyNode::Require("pangea/resource_registry".into()),
            RubyNode::Blank,
            RubyNode::Module {
                path: vec!["Pangea".into(), "Resources".into()],
                body: vec![
                    RubyNode::Module {
                        path: vec![self.module_name.clone()],
                        body: vec![
                            RubyNode::Include("Pangea::Resources::ResourceBuilder".into()),
                            RubyNode::Blank,
                            RubyNode::DefineResource {
                                tf_type: self.tf_type.clone(),
                                attrs_class: self.attrs_class.clone(),
                                outputs: self.outputs.clone(),
                                map: self.map.clone(),
                                map_present: self.map_present.clone(),
                                map_bool: self.map_bool.clone(),
                            },
                        ],
                    },
                    RubyNode::Module {
                        path: vec![self.provider_pascal.clone()],
                        body: vec![
                            RubyNode::Include(self.module_name.clone()),
                        ],
                    },
                ],
            },
            RubyNode::RegistryCall(format!("Pangea::Resources::{}", self.provider_pascal)),
        ];

        emit_file(&nodes)
    }
}

// ── Helpers ─────────────────────────────────────────────────────

fn to_pascal(s: &str) -> String {
    // Handle known provider overrides
    match s {
        "aws" => "AWS".to_string(),
        "gcp" | "google" => "Google".to_string(),
        "azurerm" => "Azure".to_string(),
        _ => {
            let mut result = String::new();
            let mut capitalize_next = true;
            for ch in s.chars() {
                if ch == '_' || ch == '-' {
                    capitalize_next = true;
                } else if capitalize_next {
                    result.extend(ch.to_uppercase());
                    capitalize_next = false;
                } else {
                    result.push(ch);
                }
            }
            result
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn types_file_has_frozen_pragma() {
        let source = TypesFileBuilder::new("porkbun")
            .class("NameserversAttributes", |c| {
                c.attribute("domain", RubyType::simple("T::String"), true)
            })
            .emit();
        assert!(source.starts_with("# frozen_string_literal: true\n"));
    }

    #[test]
    fn types_file_has_base_attributes() {
        let source = TypesFileBuilder::new("porkbun")
            .class("NameserversAttributes", |c| {
                c.attribute("domain", RubyType::simple("T::String"), true)
            })
            .emit();
        assert!(source.contains("< Pangea::Resources::BaseAttributes"));
    }

    #[test]
    fn types_file_has_module_and_class() {
        let source = TypesFileBuilder::new("porkbun")
            .class("NameserversAttributes", |c| {
                c.attribute("domain", RubyType::simple("T::String"), true)
                 .attribute("nameservers", RubyType::array(RubyType::simple("T::String")), true)
            })
            .emit();
        assert!(source.contains("module Pangea::Resources::Porkbun::Types"));
        assert!(source.contains("class NameserversAttributes"));
        assert!(source.contains("attribute :domain, T::String"));
        assert!(source.contains("attribute :nameservers, T::Array.of(T::String)"));
    }

    #[test]
    fn types_file_optional_attributes() {
        let source = TypesFileBuilder::new("aws")
            .class("VpcAttributes", |c| {
                c.attribute("cidr_block", RubyType::simple("T::String"), true)
                 .attribute("description", RubyType::simple("T::String"), false)
            })
            .emit();
        assert!(source.contains("attribute :cidr_block, T::String"));
        assert!(source.contains("attribute? :description, T::String.optional"));
    }

    #[test]
    fn types_file_aws_module_name() {
        let source = TypesFileBuilder::new("aws")
            .class("VpcAttributes", |c| c.attribute("id", RubyType::simple("T::String"), true))
            .emit();
        assert!(source.contains("module Pangea::Resources::AWS::Types"));
        assert!(source.contains("T = Pangea::Resources::AWS::Types"));
    }

    #[test]
    fn resource_file_has_define_resource() {
        let source = ResourceFileBuilder::new("porkbun", "porkbun_nameservers", "nameservers")
            .map(vec!["domain", "nameservers"])
            .emit();
        assert!(source.contains("define_resource :porkbun_nameservers"));
        assert!(source.contains("attributes_class: Porkbun::Types::NameserversAttributes"));
        assert!(source.contains("map: [:domain, :nameservers]"));
    }

    #[test]
    fn resource_file_has_registry_call() {
        let source = ResourceFileBuilder::new("porkbun", "porkbun_nameservers", "nameservers")
            .emit();
        assert!(source.contains("Pangea::ResourceRegistry.register_module(Pangea::Resources::Porkbun)"));
    }

    #[test]
    fn resource_file_has_includes() {
        let source = ResourceFileBuilder::new("porkbun", "porkbun_nameservers", "nameservers")
            .emit();
        assert!(source.contains("include Pangea::Resources::ResourceBuilder"));
        assert!(source.contains("include PorkbunNameservers"));
    }

    #[test]
    fn resource_file_with_all_categories() {
        let source = ResourceFileBuilder::new("aws", "aws_vpc", "vpc")
            .map(vec!["cidr_block"])
            .map_present(vec!["description", "tags"])
            .map_bool(vec!["enable_dns_support"])
            .emit();
        assert!(source.contains("map: [:cidr_block]"));
        assert!(source.contains("map_present: [:description, :tags]"));
        assert!(source.contains("map_bool: [:enable_dns_support]"));
    }

    #[test]
    fn pascal_case_conversion() {
        assert_eq!(to_pascal("aws"), "AWS");
        assert_eq!(to_pascal("porkbun"), "Porkbun");
        assert_eq!(to_pascal("hcloud"), "Hcloud");
        assert_eq!(to_pascal("azurerm"), "Azure");
        assert_eq!(to_pascal("my_provider"), "MyProvider");
    }
}
