//! File-level emission — turns a list of nodes into a complete Ruby source file.

use crate::node::RubyNode;

/// Emit a list of Ruby nodes as a complete source file.
///
/// Nodes are separated by newlines. The output is a valid Ruby source
/// file ready to be written to disk.
#[must_use]
pub fn emit_file(nodes: &[RubyNode]) -> String {
    let mut lines: Vec<String> = Vec::with_capacity(nodes.len());
    for node in nodes {
        lines.push(node.emit(0));
    }
    let mut out = lines.join("\n");
    // Ensure trailing newline
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::RubyType;

    #[test]
    fn emit_complete_types_file() {
        let nodes = vec![
            RubyNode::FrozenStringLiteral,
            RubyNode::Comment("Code generated by pangea-forge. DO NOT EDIT.".into()),
            RubyNode::Blank,
            RubyNode::Require("pangea/resources/base_attributes".into()),
            RubyNode::Blank,
            RubyNode::Module {
                path: vec!["Pangea".into(), "Resources".into(), "Porkbun".into(), "Types".into()],
                body: vec![
                    RubyNode::Include("Dry.Types()".into()),
                    RubyNode::Blank,
                    RubyNode::Class {
                        name: "NameserversAttributes".into(),
                        parent: Some("Pangea::Resources::BaseAttributes".into()),
                        body: vec![
                            RubyNode::ConstAssign {
                                name: "T".into(),
                                value: "Pangea::Resources::Porkbun::Types".into(),
                            },
                            RubyNode::Blank,
                            RubyNode::Attribute {
                                name: "domain".into(),
                                type_expr: RubyType::simple("T::String"),
                                required: true,
                            },
                            RubyNode::Attribute {
                                name: "nameservers".into(),
                                type_expr: RubyType::array(RubyType::simple("T::String")),
                                required: true,
                            },
                        ],
                    },
                ],
            },
        ];

        let output = emit_file(&nodes);

        // Verify structure
        assert!(output.starts_with("# frozen_string_literal: true\n"));
        assert!(output.contains("require 'pangea/resources/base_attributes'"));
        assert!(output.contains("module Pangea::Resources::Porkbun::Types"));
        assert!(output.contains("  include Dry.Types()"));
        assert!(output.contains("  class NameserversAttributes < Pangea::Resources::BaseAttributes"));
        assert!(output.contains("    T = Pangea::Resources::Porkbun::Types"));
        assert!(output.contains("    attribute :domain, T::String"));
        assert!(output.contains("    attribute :nameservers, T::Array.of(T::String)"));
        assert!(output.ends_with('\n'));
    }
}
