//! RBS file builders — structurally correct `.rbs` signature file generation.
//!
//! Parallels `TypesFileBuilder` but emits RBS syntax consumed by `steep`
//! and the `rbs` gem for static type checking of generated pangea resources.
//!
//! The compiler enforces the same invariants as the Ruby builders:
//! - Attributes only exist inside a class
//! - Classes only exist inside the module chain
//! - Module nesting is deterministic and balanced

use crate::rbs_types::RbsType;

/// Builds a `types.rbs` file paralleling a `types.rb` emitted by
/// `TypesFileBuilder`. Structure (fixed):
///
/// ```text
/// # Code generated by pangea-forge. DO NOT EDIT.
/// module Pangea
///   module Resources
///     module <Provider>
///       module Types
///         class <ClassName> < Pangea::Resources::BaseAttributes
///           attr_reader <field>: <RbsType>[?]
///           ...
///         end
///       end
///     end
///   end
/// end
/// ```
pub struct TypesRbsFileBuilder {
    provider_pascal: String,
    classes: Vec<RbsClassDef>,
}

struct RbsClassDef {
    name: String,
    attributes: Vec<(String, RbsType, bool)>,
}

/// Builder context for adding attributes to an RBS class.
/// Only attribute-level operations are available.
pub struct RbsClassBuilder {
    attributes: Vec<(String, RbsType, bool)>,
}

impl RbsClassBuilder {
    /// Add an attribute. When `required` is false, the emitted type is nilable.
    #[must_use]
    pub fn attribute(mut self, name: &str, ty: RbsType, required: bool) -> Self {
        self.attributes.push((name.to_string(), ty, required));
        self
    }
}

impl TypesRbsFileBuilder {
    /// Create a new RBS types file builder for a provider module.
    #[must_use]
    pub fn new(provider: &str) -> Self {
        Self {
            provider_pascal: to_pascal(provider),
            classes: Vec::new(),
        }
    }

    /// Add a class signature. The closure receives an `RbsClassBuilder`
    /// restricted to attribute operations.
    #[must_use]
    pub fn class(mut self, name: &str, f: impl FnOnce(RbsClassBuilder) -> RbsClassBuilder) -> Self {
        let builder = f(RbsClassBuilder { attributes: Vec::new() });
        self.classes.push(RbsClassDef {
            name: name.to_string(),
            attributes: builder.attributes,
        });
        self
    }

    /// Emit the complete RBS source file (deterministic, trailing newline).
    #[must_use]
    pub fn emit(&self) -> String {
        let mut out = String::new();
        out.push_str("# Code generated by pangea-forge. DO NOT EDIT.\n");
        out.push_str("module Pangea\n");
        out.push_str("  module Resources\n");
        out.push_str(&format!("    module {}\n", self.provider_pascal));
        out.push_str("      module Types\n");

        for (idx, class_def) in self.classes.iter().enumerate() {
            if idx > 0 {
                out.push('\n');
            }
            out.push_str(&format!(
                "        class {} < Pangea::Resources::BaseAttributes\n",
                class_def.name,
            ));
            for (name, ty, required) in &class_def.attributes {
                let rendered = if *required {
                    ty.emit()
                } else {
                    RbsType::nilable(ty.clone()).emit()
                };
                out.push_str(&format!("          attr_reader {name}: {rendered}\n"));
            }
            out.push_str("        end\n");
        }

        out.push_str("      end\n");
        out.push_str("    end\n");
        out.push_str("  end\n");
        out.push_str("end\n");
        out
    }
}

fn to_pascal(s: &str) -> String {
    match s {
        "aws" => "AWS".to_string(),
        "gcp" | "google" => "Google".to_string(),
        "azurerm" => "Azure".to_string(),
        _ => {
            let mut result = String::new();
            let mut capitalize_next = true;
            for ch in s.chars() {
                if ch == '_' || ch == '-' {
                    capitalize_next = true;
                } else if capitalize_next {
                    result.extend(ch.to_uppercase());
                    capitalize_next = false;
                } else {
                    result.push(ch);
                }
            }
            result
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_generated_header() {
        let src = TypesRbsFileBuilder::new("porkbun")
            .class("NameserversAttributes", |c| {
                c.attribute("domain", RbsType::named("String"), true)
            })
            .emit();
        assert!(src.starts_with("# Code generated by pangea-forge. DO NOT EDIT.\n"));
    }

    #[test]
    fn emits_module_chain() {
        let src = TypesRbsFileBuilder::new("akeyless")
            .class("StaticSecretAttributes", |c| {
                c.attribute("path", RbsType::named("String"), true)
            })
            .emit();
        assert!(src.contains("module Pangea\n"));
        assert!(src.contains("  module Resources\n"));
        assert!(src.contains("    module Akeyless\n"));
        assert!(src.contains("      module Types\n"));
    }

    #[test]
    fn class_extends_base_attributes() {
        let src = TypesRbsFileBuilder::new("aws")
            .class("VpcAttributes", |c| {
                c.attribute("cidr_block", RbsType::named("String"), true)
            })
            .emit();
        assert!(src.contains("class VpcAttributes < Pangea::Resources::BaseAttributes"));
    }

    #[test]
    fn required_attribute_has_no_nilable() {
        let src = TypesRbsFileBuilder::new("aws")
            .class("VpcAttributes", |c| {
                c.attribute("cidr_block", RbsType::named("String"), true)
            })
            .emit();
        assert!(src.contains("attr_reader cidr_block: String\n"));
        assert!(!src.contains("cidr_block: String?"));
    }

    #[test]
    fn optional_attribute_is_nilable() {
        let src = TypesRbsFileBuilder::new("aws")
            .class("VpcAttributes", |c| {
                c.attribute("description", RbsType::named("String"), false)
            })
            .emit();
        assert!(src.contains("attr_reader description: String?\n"));
    }

    #[test]
    fn optional_array_nilable_wraps_whole() {
        let src = TypesRbsFileBuilder::new("aws")
            .class("TagsAttributes", |c| {
                c.attribute("tags", RbsType::array(RbsType::named("String")), false)
            })
            .emit();
        assert!(src.contains("attr_reader tags: Array[String]?\n"));
    }

    #[test]
    fn provider_name_maps_aws_to_pascal_all_caps() {
        let src = TypesRbsFileBuilder::new("aws")
            .class("X", |c| c.attribute("id", RbsType::named("String"), true))
            .emit();
        assert!(src.contains("module AWS\n"));
    }

    #[test]
    fn deterministic_output() {
        let build = || {
            TypesRbsFileBuilder::new("datadog")
                .class("MonitorAttributes", |c| {
                    c.attribute("name", RbsType::named("String"), true)
                        .attribute("type", RbsType::named("String"), true)
                        .attribute("tags", RbsType::array(RbsType::named("String")), false)
                })
                .emit()
        };
        assert_eq!(build(), build());
    }

    #[test]
    fn emits_trailing_newline() {
        let src = TypesRbsFileBuilder::new("x")
            .class("Y", |c| c.attribute("z", RbsType::named("String"), true))
            .emit();
        assert!(src.ends_with("end\n"));
    }

    #[test]
    fn multiple_classes_separated_by_blank() {
        let src = TypesRbsFileBuilder::new("x")
            .class("A", |c| c.attribute("a", RbsType::named("String"), true))
            .class("B", |c| c.attribute("b", RbsType::named("Integer"), true))
            .emit();
        assert!(src.contains("class A < Pangea::Resources::BaseAttributes"));
        assert!(src.contains("class B < Pangea::Resources::BaseAttributes"));
    }

    #[test]
    fn balanced_module_and_class_ends() {
        let src = TypesRbsFileBuilder::new("x")
            .class("Y", |c| c.attribute("z", RbsType::named("String"), true))
            .emit();
        let opens = src.matches("module ").count() + src.matches("class ").count();
        let ends = src.matches("end\n").count();
        assert_eq!(opens, ends, "opens must match ends\n{src}");
    }
}
